# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for berserker CLI (console mode)

import os
import sys

# Block: Analysis
a = Analysis(
    ["berserker/cli_entry.py"],
    pathex=[os.path.abspath(".")],
    binaries=[],
    datas=[
        ("berserker/py.typed", "berserker"),
        ("qwen.tiktoken", "."),  # Include qwen.tiktoken next to exe
        ("berserker/agent/prompts", "berserker/agent/prompts"),  # External prompt files
        ("berserker/agent/configs", "berserker/agent/configs"),  # Agents config
        ("berserker/assets", "berserker/assets"),  # Logo and icon assets
    ],    hiddenimports=[
        # Core packages
        "berserker.agent",
        "berserker.auth",
        "berserker.bus",
        "berserker.cli",
        # CLI subcommands (explicitly listed for PyInstaller)
        "berserker.cli.cli",
        "berserker.cli.conversation",
        "berserker.cli.serve",
        "berserker.cli.models_providers",
        "berserker.cli.session_cmd",
        "berserker.cli.agent_cmd",
        "berserker.cli.auth_cmd",
        "berserker.cli.mcp_cmd",
        "berserker.cli.maintenance_cmd",
        "berserker.cli.github_cmd",
        "berserker.cli.plugin_cmd",
        "berserker.cli.stats_cmd",
        "berserker.config",
        "berserker.file",
        "berserker.git",
        "berserker.id",
        "berserker.logging_config",
        "berserker.lsp",
        "berserker.mcp",
        "berserker.paths",
        "berserker.permission",
        "berserker.plugin_system",
        "berserker.plugin",
        "berserker.provider",
        # Dynamically imported provider modules (via importlib.import_module)
        "berserker.provider.openai",
        "berserker.provider.openai_compatible",
        "berserker.provider.anthropic",
        "berserker.server",
        "berserker.session",
        "berserker.session.fallback_estimator",
        "berserker.session.qwen_tokenizer",
        "berserker.session.benchmark_tokenizer",
        "berserker.share",
        "berserker.storage",
        "berserker.tool",
        # Tool submodules (explicitly listed for safety)
        "berserker.tool.base",
        "berserker.tool.registry",
        "berserker.tool.bash",
        "berserker.tool.edit_complex",
        "berserker.tool.file_simple",
        "berserker.tool.file_ops",
        "berserker.tool.search",
        "berserker.tool.skill",
        "berserker.tool.git",
        "berserker.tool.task",
        "berserker.tool.lsp",
        "berserker.tool.auxiliary",
        "berserker.tool.selection",
        "berserker.tool.todo",
        "berserker.tool.init",
        "berserker.tool.truncate",
        "berserker.workspace",
        # Display adapter (used by CLI conversation)
        "berserker.display",
        "berserker.display.adapter",
        # Command system
        "berserker.command",
        "berserker.command.types",
        "berserker.command.frontmatter",
        "berserker.command.discovery",
        "berserker.command.registry",
        "berserker.command.builtin",
        "berserker.command.processor",
        "berserker.command.formatter",
        # Plugin system (dynamically loaded plugins)
        "berserker.plugin_system",  # Session submodules
        "berserker.session.snapshot",
        "berserker.session.message_utils",
        "berserker.session.history",
        "berserker.session.token_counter",
        "berserker.session.instruction",
        "berserker.session.parts",
        "berserker.session.title_gen",
        # Storage submodules
        "berserker.storage.db",
        "berserker.storage.crud",
        "berserker.storage.migrations",
        "berserker.storage.schema",
        # Workspace submodules
        "berserker.workspace.manager",
        # Provider registry (dynamic provider loading)
        "berserker.provider.registry",
        # Config submodules
        "berserker.config.loader",
        "berserker.config.jsonc",
        "berserker.config.substitution",
        # Paths submodules
        "berserker.paths.resolver",
        # ID submodules
        "berserker.id.generator",
        # Agent submodules
        "berserker.agent.adapter",
        "berserker.agent.agents_md",
        "berserker.agent.base",
        "berserker.agent.compaction",
        "berserker.agent.config",
        "berserker.agent.constants",
        "berserker.agent.discovery",
        "berserker.agent.events",
        "berserker.agent.exceptions",
        "berserker.agent.executor",
        "berserker.agent.factory",
        "berserker.agent.generator",
        "berserker.agent.init_prompt",  # Plugin implementations
        "berserker.agent.manager",
        "berserker.agent.messaging",
        "berserker.agent.middleware",
        "berserker.agent.modes",
        "berserker.agent.monitor",
        "berserker.agent.orchestrator",
        "berserker.agent.prompt_loader",
        "berserker.agent.prompts",
        "berserker.agent.registry",
        "berserker.agent.result_aggregator",
        "berserker.agent.schema",
        "berserker.plugin.session_timer",
        # Standard library modules that might be needed
        "argparse",
        "json",
        "os",
        "sys",
        "typing",
        "importlib",
        "datetime",
        "sqlite3",
        "logging",
        "threading",
        "subprocess",
        "signal",
        # Third-party packages used by CLI mode
        "openai",
        "openai._legacy_response",
        "openai._streaming",
        "openai._base_client",
        "openai._models",
        "openai._utils",
        "openai._constants",
        "openai._exceptions",
        "openai._response",
        "openai._qs",
        "openai._files",
        "openai._compat",
        "openai.pagination",
        "openai._typing",
        "openai._proxy",
        "openai._wrappers",
        "openai.types",
        "openai.types.chat",
        "openai.types.chat.chat_completion",
        "openai.types.chat.chat_completion_chunk",
        "openai.types.chat.chat_completion_message",
        "openai.types.chat.chat_completion_message_param",
        "openai.types.chat.chat_completion_role",
        "openai.types.chat.chat_completion_tool_param",
        "openai.types.chat.chat_completion_stream_options_param",
        "openai.types.completion",
        "openai.types.create_embedding_response",
        "openai.types.model",
        "openai.types.moderation",
        "openai.types.images_response",
        "openai.types.audio",
        "anthropic",
        "anthropic._constants",
        "anthropic._compat",
        "anthropic._client",
        "anthropic._base_client",
        "anthropic._models",
        "anthropic._utils",
        "anthropic._streaming",
        "anthropic._response",
        "anthropic._exceptions",
        "anthropic._legacy_response",
        "anthropic.pagination",
        "anthropic._qs",
        "anthropic._files",
        "anthropic._wrappers",
        "anthropic.types",
        "anthropic.types.message",
        "anthropic.types.messages",
        "yaml",
        "yaml.resolver",
        "yaml.constructor",
        "yaml.representer",
        "yaml.scanner",
        "yaml.parser",
        "yaml.composer",
        "yaml.emitter",
        "yaml.serializer",
        "yaml.loader",
        "yaml.dumper",
        "yaml.cyaml",
        "jsonschema",
        "jsonschema.validators",
        "jsonschema._validators",
        "jsonschema._types",
        "jsonschema._utils",
        "jsonschema._format",
        "jsonschema.exceptions",
        "jsonschema._legacy_validators",
        "jsonschema._keywords",
        "typing_extensions",
        # Additional CLI-only third-party dependencies
        "tiktoken",
        "httpx",
        "platformdirs",
        "mcp",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "unittest",
        "test",
        "PIL",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# Block: PYZ
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# Block: EXE (onefile mode, console)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="berserker",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="berserker/assets/logo.ico",
)
