# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for berserker GUI (windowed, no console)
# Pure GUI build - no CLI modules included

import os
import sys

# Block: Analysis
a = Analysis(
    ["berserker/gui_entry.py"],
    pathex=[os.path.abspath(".")],
    binaries=[],
    datas=[
        ("berserker/py.typed", "berserker"),
        ("qwen.tiktoken", "."),  # Include qwen.tiktoken next to exe
        ("berserker/agent/prompts", "berserker/agent/prompts"),  # External prompt files
        ("berserker/agent/configs", "berserker/agent/configs"),  # Agents config
        ("berserker/assets", "berserker/assets"),  # Logo and icon assets
    ],
    hiddenimports=[
        # Core packages
        "berserker.agent",
        "berserker.auth",
        "berserker.bus",
        "berserker.config",
        "berserker.git",
        "berserker.id",
        "berserker.logging_config",
        "berserker.lsp",
        "berserker.mcp",
        "berserker.paths",
        "berserker.permission",
        "berserker.plugin_system",
        "berserker.plugin",
        "berserker.provider",
        # Dynamically imported provider modules (via importlib.import_module)
        "berserker.provider.openai",
        "berserker.provider.openai_compatible",
        "berserker.provider.anthropic",
        "berserker.display",
        "berserker.display.adapter",
        # Command system
        "berserker.command",
        "berserker.command.types",
        "berserker.command.frontmatter",
        "berserker.command.discovery",
        "berserker.command.registry",
        "berserker.command.builtin",
        "berserker.command.processor",
        "berserker.command.formatter",
        "berserker.session",
        "berserker.session.fallback_estimator",
        "berserker.session.qwen_tokenizer",
        "berserker.session.benchmark_tokenizer",
        "berserker.share",
        "berserker.storage",
        "berserker.tool",
        # Tool submodules (GUI uses tools via agent execution)
        "berserker.tool.base",
        "berserker.tool.registry",
        "berserker.tool.bash",
        "berserker.tool.edit_complex",
        "berserker.tool.file_simple",
        "berserker.tool.file_ops",
        "berserker.tool.search",
        "berserker.tool.skill",
        "berserker.tool.git",
        "berserker.tool.task",
        "berserker.tool.lsp",
        "berserker.tool.auxiliary",
        "berserker.tool.selection",
        "berserker.tool.todo",
        "berserker.tool.init",
        "berserker.tool.truncate",
        "berserker.session.message_utils",
        "berserker.workspace",
        # GUI modules
        "berserker.gui",
        "berserker.gui.app",
        "berserker.gui.controller",
        "berserker.gui.main",
        "berserker.gui.chat_listbox",
        "berserker.gui.sidebar",
        "berserker.gui.state",
        "berserker.gui.md_to_plain",
        "berserker.gui.markdown_renderer",
        "berserker.gui.agent_status_panel",
        "berserker.gui.autocomplete",
        "berserker.gui.theme",
        "berserker.gui_entry",
        # Session submodules
        "berserker.session.snapshot",
        "berserker.session.history",
        "berserker.session.token_counter",
        "berserker.session.instruction",
        "berserker.session.parts",
        "berserker.session.title_gen",
        "berserker.session.context",
        "berserker.session.manager",
        # Storage submodules
        "berserker.storage.db",
        "berserker.storage.crud",
        "berserker.storage.migrations",
        "berserker.storage.schema",
        # Workspace submodules
        "berserker.workspace.manager",
        # Provider registry (dynamic provider loading)
        "berserker.provider.registry",
        # Config submodules
        "berserker.config.loader",
        "berserker.config.jsonc",
        "berserker.config.substitution",
        # Paths submodules
        "berserker.paths.resolver",
        # ID submodules
        "berserker.id.generator",
        # Agent submodules
        "berserker.agent.agents_md",
        "berserker.agent.compaction",
        "berserker.agent.executor",
        "berserker.agent.manager",
        "berserker.agent.base",
        "berserker.agent.modes",
        "berserker.agent.exceptions",
        "berserker.agent.constants",
        "berserker.agent.config",
        "berserker.agent.registry",
        "berserker.agent.factory",
        "berserker.agent.orchestrator",
        "berserker.agent.middleware",
        "berserker.agent.result_aggregator",
        "berserker.agent.adapter",
        "berserker.agent.discovery",
        "berserker.agent.events",
        "berserker.agent.generator",
        "berserker.agent.schema",
        "berserker.agent.prompts",
        "berserker.agent.init_prompt",
        # Plugin implementations
        "berserker.plugin.session_timer",
        # Standard library modules that might be needed
        "argparse",
        "json",
        "os",
        "sys",
        "typing",
        "importlib",
        "datetime",
        "sqlite3",
        "logging",
        "threading",
        "subprocess",
        "signal",
        # wxPython GUI framework modules
        "wx",
        "wx.html",
        "wx.html2",
        "wx.adv",
        "wx.core",
        "wx.lib",
        # Third-party packages used by shared modules
        "openai",
        "openai._legacy_response",
        "openai._streaming",
        "openai._base_client",
        "openai._models",
        "openai._utils",
        "openai._constants",
        "openai._exceptions",
        "openai._response",
        "openai._qs",
        "openai._files",
        "openai._compat",
        "openai.pagination",
        "openai._typing",
        "openai._proxy",
        "openai._wrappers",
        "openai.types",
        "openai.types.chat",
        "openai.types.chat.chat_completion",
        "openai.types.chat.chat_completion_chunk",
        "openai.types.chat.chat_completion_message",
        "openai.types.chat.chat_completion_message_param",
        "openai.types.chat.chat_completion_role",
        "openai.types.chat.chat_completion_tool_param",
        "openai.types.chat.chat_completion_stream_options_param",
        "openai.types.completion",
        "openai.types.create_embedding_response",
        "openai.types.model",
        "openai.types.moderation",
        "openai.types.images_response",
        "openai.types.audio",
        "anthropic",
        "anthropic._constants",
        "anthropic._compat",
        "anthropic._client",
        "anthropic._base_client",
        "anthropic._models",
        "anthropic._utils",
        "anthropic._streaming",
        "anthropic._response",
        "anthropic._exceptions",
        "anthropic._legacy_response",
        "anthropic.pagination",
        "anthropic._qs",
        "anthropic._files",
        "anthropic._wrappers",
        "anthropic.types",
        "anthropic.types.message",
        "anthropic.types.messages",
        "yaml",
        "yaml.resolver",
        "yaml.constructor",
        "yaml.representer",
        "yaml.scanner",
        "yaml.parser",
        "yaml.composer",
        "yaml.emitter",
        "yaml.serializer",
        "yaml.loader",
        "yaml.dumper",
        "yaml.cyaml",
        "jsonschema",
        "jsonschema.validators",
        "jsonschema._validators",
        "jsonschema._types",
        "jsonschema._utils",
        "jsonschema._format",
        "jsonschema.exceptions",
        "jsonschema._legacy_validators",
        "jsonschema._keywords",
        "mistune",
        "mistune.plugins.table",
        "typing_extensions",
        # Token counting (used by session/token_counter.py, tool/truncate.py)
        "tiktoken",
        # Additional shared third-party dependencies
        "httpx",
        "platformdirs",
        "mcp",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "unittest",
        "test",
        "PIL",
        # Exclude CLI modules
        "berserker.cli",
        "berserker.cli.cli",
        "berserker.cli.conversation",
        "berserker.cli.serve",
        "berserker.cli.models_providers",
        "berserker.cli.session_cmd",
        "berserker.cli.agent_cmd",
        "berserker.cli.auth_cmd",
        "berserker.cli.mcp_cmd",
        "berserker.cli.maintenance_cmd",
        "berserker.cli.github_cmd",
        "berserker.cli.plugin_cmd",
        "berserker.cli.stats_cmd",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# Block: PYZ
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# Block: EXE (onefile mode, windowed — single executable)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="berserker-gui",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window - pure GUI application
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="berserker/assets/logo.ico",
)
